Repository t1nkl-courses/JS_lessons, pull requests merged in 2023-04, with the labels that each got.

#3 Feature/working
  index.html
  lesson_16/index.html
  lesson_16/tasks/task1.html
  lesson_16/tasks/task2.html
  lesson_16/tasks/task3.html
  lesson_16/tasks/task4.html
Labels: enhancement

#4 Feature/working
  index.html
  lesson_16/tasks/task3.html
  lesson_17/index.html
  lesson_17/tasks/task1.html
  lesson_17/tasks/task2.html
  lesson_17/tasks/task3.html
  lesson_17/tasks/task4.html
  lesson_17/tasks/task5.html
Labels: bug, enhancement

#5 lesson 17 - tasks 1-5 - init
  lesson_17/tasks/task1.html
  lesson_17/tasks/task2.html
  lesson_17/tasks/task3.html
  lesson_17/tasks/task4.html
  lesson_17/tasks/task5.html
Labels: enhancement

#6 lesson 18
  .gitignore
  lesson_18/index.html
  lesson_18/tasks/task1.html
  lesson_18/tasks/task2.html
  lesson_18/tasks/task3.html
  lesson_18/tasks/task4.html
  lesson_18/tasks/task5.html
  lesson_18/tasks/task6.html
  lesson_18/tasks/task7.html
Labels: enhancement

#8 lesson 18 - tasks fixes
  lesson_18/tasks/task2.html
  lesson_18/tasks/task3.html
  lesson_18/tasks/task6.html
Labels: bug

#9 lesson 19 / lesson 21
  index.html
  lesson_19/index.html
  lesson_19/tasks/task1.html
  lesson_19/tasks/task2.html
  lesson_19/tasks/task3.html
  lesson_19/tasks/task4.html
  lesson_19/tasks/task5.html
  lesson_21/index.html
  lesson_21/tasks/task1.html
  lesson_21/tasks/task2.html
  lesson_21/tasks/task3.html
  lesson_21/tasks/task4.html
  lesson_21/tasks/task5.html
  lesson_21/tasks/task6.html
Labels: enhancement

#10 lesson 22 / lesson 23
  index.html
  lesson_22/index.html
  lesson_22/tasks/task1.html
  lesson_22/tasks/task2.html
  lesson_22/tasks/task3.html
  lesson_23/index.html
  lesson_23/tasks/task1.html
  lesson_23/tasks/task2.html
Labels: enhancement
